name = "CompressedSparseBlocks"
uuid = "c9633620-f88e-4e67-b3af-074911471b78"
authors = ["Dimitris Floros <fcdimitr@ece.auth.gr>", "Nikos Pitsianis <pitsiani@ece.auth.gr>", "Xiaobai Sun <xiaobai@cs.duke.edu>"]
version = "0.1.0"

[deps]
CSB_jll = "a883dece-cb75-578c-a4af-c9463aa1e20e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CSB_jll = "1"
DocStringExtensions = "0.8"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
